### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/py_decl#1]
* [x] refactor uf2 support into a standard IOSteam? reader that works just like open() on a bin file
* [x] make this work on MicroPython?
* [x] refactor to a class/library (half way done, kinda)
* [ ] add support for pins and such
* [ ] add tests, CI and packaging
* [ ] make `UF2Reader` lazy?

**Comment by Gadgetoid** [comment]
TO make this work *on* MicroPython, it just needs a new reader:

```python
class FlashReader():
    def __init__(self):
        self.mem = machine.mem8
        self.offset = 0
        self.buf_len = 16
        self.buf = bytearray(self.buf_len)
        
    def seek(self, offset):
        self.offset = offset
        
    def read(self, length):
        buf = bytearray(length) if length > self.buf_len else self.buf
        for i in range(length):
            buf[i] = self.mem[FLASH_START_ADDR + self.offset]
            self.offset += 1
        return bytes(buf[:length])
```

**Comment by Gadgetoid** [comment]
Revised version now added to py_decl:

```python
class MemoryReader():
    def __init__(self, mem, global_offset=FLASH_START_ADDR):
        self.mem = mem
        self.offset = 0
        self.buf_len = 16
        self.global_offset = global_offset
        self.buf = bytearray(self.buf_len)
        
    def seek(self, offset):
        self.offset = offset
        
    def read(self, length):
        buf = bytearray(length) if length > self.buf_len else self.buf
        for i in range(length):
            buf[i] = self.mem[self.global_offset + self.offset]
            self.offset += 1
        return bytes(buf[:length])
```

Note: UF2Reader does not work on MicroPython because you can't subclass `BytesIO` (call to `BytesIO.__init__` fails).
